spring.application.name=AddressBookApp

spring.datasource.url=jdbc:mysql://localhost:3306/addressbookdb
spring.datasource.username=root
spring.datasource.password=yukta@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver